routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.layout.login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(array('prefix' => 'dashboard','as'=>'admin.' ,'middleware' => 'auth'), function() {

    Route::get('/', 'indexController@index')->name('layout.main');

    Route::resource('users', 'userController');
    Route::resource('guarantors', 'guarantorController');
    Route::resource('clients', 'clientController');
    Route::resource('mediators', 'mediatorController');
    Route::resource('settings', 'settingController');

    Route::resource('clearances', 'clearanceController');
    Route::resource('car_contracts', 'car_contractController');
    Route::resource('card_contracts', 'card_contractController');
    Route::any('/card_sadad/{id}','card_contractController@sadad' )->name('card_contracts.sadad');

    Route::post('/sadad-qests/{id}','card_contractController@qest_sadad' )->name('card_contracts.sadad_qests');
    Route::any('/sadad-cars/{id}','car_contractController@qest_sadad' )->name('car_contracts.sadad_qests');


    Route::get('/card','card_contractController@qast' )->name('card_contracts.qests');

    Route::get('/sadad/{id}','car_contractController@sadad' )->name('car_contracts.sadad');
    Route::get('/card_report/{id}','card_contractController@report' )->name('card_contracts.report');

    Route::get('/report/{id}','car_contractController@report' )->name('car_contracts.report');
    Route::get('/contract/{id}','car_contractController@print' )->name('car_contracts.print');
    Route::get('/card_contract/{id}','card_contractController@print' )->name('card_contracts.print');

    Route::get('/client_sanad/{id}','car_contractController@client_sanad' )->name('car_contracts.client_sanad');
    Route::get('/guarantor_sanad/{id}','car_contractController@guarantor_sanad' )->name('car_contracts.guarantor_sanad');

    Route::get('/card_client_sanad/{id}','card_contractController@client_sanad' )->name('card_contracts.client_sanad');
    Route::get('/card_guarantor_sanad/{id}','card_contractController@guarantor_sanad' )->name('card_contracts.guarantor_sanad');
    Route::any('/collected_premiums','ReportController@premiums')->name('reports.collected_premiums');

});

app/Http/Controllers/card_contractController.php
<?php

namespace App\Http\Controllers;

use App\Activity;
use App\City;
use App\Client;
use App\CollectPremium;
use App\Contract;
use App\Guarantor;
use App\Http\Helpers\num_to_ar;
use App\Mediator;
use App\Payment;
use App\User;
use function GuzzleHttp\Promise\all;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Hash;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use GeniusTS\HijriDate\Date;

class card_contractController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.card_contracts.index')->with('card_contracts',Contract::where('type','card')->orderByDesc('created_at')->get());
    }

    public function qast(){

        $futureday= date('Y-m-d', strtotime("+15 days"));
        //  dd($futureday);
        $qests=Payment::where('date','<=',$futureday)->where('pay',0)->get();

        return view('admin.card_contracts.view',compact('qests'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $guarantors=Guarantor::pluck('name','id')->toArray();
        $clients=Client::pluck('name','id')->toArray();
        $mediators=Mediator::pluck('name','id')->toArray();

        return view('admin.card_contracts.add',compact('guarantors','clients','mediators'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       // dd($request->all());
        $this->validate($request,[



        ]);
        $inputs=$request->all();
        $user_id=Auth::user()->id;
        $contract= Contract::create($inputs);
        $client_id=$inputs['client_id'];
        $start_date=$inputs['start_date'];

        $class=$inputs['class'];
        $number=$inputs['number'];
        $added_value=$inputs['added_value'];
        $months_count=$inputs['months_count'];
        $amount=$class*$number;
        $total_amount=$amount+$added_value;
        $onepay=($amount+$added_value)/$months_count;



        $contract->update([
            'type'=>'card',
            'amount'=>$amount
        ]);


        for ($i=0;$i<$months_count;$i++)

        {
            Payment::create([
                'user_id'=>$user_id,
                'client_id'=>$client_id,
                'contract_id'=>$contract->id,
                'one_pay'=>$onepay,
                'amount'=>$total_amount,
                'date'=>$start_date
            ]);
            $total_amount=$total_amount-$onepay;
            $start_date=Carbon::parse($start_date)->addMonths(1);

              }
        $text=' اضافه عقد  بطاقات '. $contract->id;
        Activity($text);

        alert()->success('تم اضافة العقد بنجاح !')->autoclose(5000);
//        return back();
/////////////////////////////////////////////////////////////
        $numbers=new num_to_ar(($contract->class*$contract->number)+$contract->added_value,"male");

        $total=$numbers->convert_number().'ريال';
        $contract_date1= $contract->created_at;

        $today_date = $contract_date1->format('d-m-Y');
        $payment=Payment::where('contract_id',$contract->id)->first();
        $numbersx=new num_to_ar($payment->one_pay,"male");
        $one_pay=$numbersx->convert_number().'ريال';
        $date = \GeniusTS\HijriDate\Hijri::convertToHijri($today_date)->format('d-m-Y');
        $dayname = $contract_date1->locale('ar')->dayName;
        // dd($day);
      /*  if ($day=='Sat') {
            $dayname = 'السبت';
        }else  if ($day=='Sun') {
            $dayname = 'الاحد';
        }else  if ($day=='Mon') {
            $dayname = 'الاثنين';
        }else  if ($day=='Tue') {
            $dayname = 'الثلاتاء';
        }else  if ($day=='Wed') {
            $dayname = 'الاربعاء';
        }else  if ($day=='Thu') {
            $dayname = 'الخميس';
        }else  if ($day=='Fri') {
            $dayname = 'الجمعة';
        }*/

//dd($dayname);

        return view('admin.card_contracts.contract',compact('total','one_pay','today_date','contract','date','payment','dayname','payment'));



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $qests=Payment::where('contract_id',$id)->get();
        return view('admin.card_contracts.view',compact('qests'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $contract=Contract::find($id);
        $guarantors=Guarantor::pluck('name','id')->toArray();
        $mediators=Mediator::pluck('name','id')->toArray();
        $clients=Client::pluck('name','id')->toArray();
        return view('admin.card_contracts.edit',compact('clients','guarantors','mediators','contract'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       // dd($request->all());
        $contract=Contract::find($id);

        $inputs=$request->all();
        $contract->update($inputs);
        $text=' تعديل العقد '. $contract->id;
        Activity($text);
        alert()->success('تم تعديل  العقد بنجاح !')->autoclose(5000);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $contract=Contract::find($id);
        $contract->delete();

        $text=' حذف العقد '. $contract->id;
        Activity($text);
        alert()->success('تم حذف العقد بنجاح');
        return back();
    }
    public function sadad(Request $request,$id)
    {
        $payment=Payment::find($id);
       $payment->update([
            'pay'=>1,
           'updated_at'=>Date::today()->format('d-m-Y')
        ]);
        $qests=Payment::where('contract_id',$id)->get();
//        return back();

CollectPremium::create([
    'date'=>Date::today()->format('d-m-Y'),
    'payment_id'=>$payment->id,
    'amount'=>$payment->amount,
]);
        $qest_num=$request['key'];

        return view('admin.card_contracts.sadad',compact('payment','qest_num'));


    }

    public function report($id)
    {

        $contract=Contract::find($id);
        $paymemts_paid=Payment::where('contract_id',$id)->where('pay',1)->count();
        $paymemts_notpaid=Payment::where('contract_id',$id)->where('pay',0)->count();
        $payments=Payment::where('contract_id',$id)->where('pay',0)->get();
        $paid_1=Payment::where('contract_id',$id)->where('pay',1)->sum('one_pay');
        $paid=ceil($paid_1);
        $not_paid_1=Payment::where('contract_id',$id)->where('pay',0)->sum('one_pay');
        $not_paid=ceil($not_paid_1);



        return view('admin.card_contracts.report',compact('contract','paymemts_paid','paymemts_notpaid','payments','paid','not_paid'));

    }
    public function print($id){
        $contract=Contract::find($id);
        $numbers=new num_to_ar(($contract->class*$contract->number)+$contract->added_value,"male");

        $total=$numbers->convert_number().'ريال';
        $contract_date1= $contract->created_at;

        $today_date = $contract_date1->format('d-m-Y');
        $payment=Payment::where('contract_id',$contract->id)->first();
        $numbersx=new num_to_ar($payment->one_pay,"male");
        $one_pay=$numbersx->convert_number().'ريال';
        $date = \GeniusTS\HijriDate\Hijri::convertToHijri($today_date)->format('d-m-Y');
        $dayname = $contract_date1->locale('ar')->dayName;
      // dd($day);
      /*  if ($day=='Sat') {
            $dayname = 'السبت';
        }else  if ($day=='Sun') {
            $dayname = 'الاحد';
        }else  if ($day=='Mon') {
            $dayname = 'الاثنين';
        }else  if ($day=='Tue') {
            $dayname = 'الثلاتاء';
        }else  if ($day=='Wed') {
            $dayname = 'الاربعاء';
        }else  if ($day=='Thu') {
            $dayname = 'الخميس';
        }else  if ($day=='Fri') {
            $dayname = 'الجمعة';
        }*/

//dd($dayname);

        return view('admin.card_contracts.contract',compact('total','one_pay','today_date','contract','date','payment','dayname','payment'));
    }
    public  function guarantor_sanad($id){

        $contract=Contract::find($id);
        $numbers=new num_to_ar(($contract->class*$contract->number)+$contract->added_value,"male");
        $total=$numbers->convert_number().'ريال';

        $contract_date1= $contract->created_at;

        $today_date = $contract_date1->format('d-m-Y');
        $payment=Payment::where('contract_id',$contract->id)->first();
        $numbersx=new num_to_ar($payment->one_pay,"male");
        $one_pay=$numbersx->convert_number().'ريال';
        $date = \GeniusTS\HijriDate\Hijri::convertToHijri($today_date)->format('d-m-Y');
        $day = $contract_date1->format('D');
                $dayname = $contract_date1->locale('ar')->dayName;

        //    dd($payment);
   /*     if ($day=='Sta') {
            $dayname = 'السبت';
        }else  if ($day=='Sun') {
            $dayname = 'الاحد';
        }else  if ($day=='Mon') {
            $dayname = 'الاثنين';
        }else  if ($day=='Tue') {
            $dayname = 'الثلاتاء';
        }else  if ($day=='Wen') {
            $dayname = 'الاربعاء';
        }else  if ($day=='Thr') {
            $dayname = 'الخميس';
        }else  if ($day=='Fri') {
            $dayname = 'الجمعة';
        }*/

resources/views/admin/card_contracts/add.blade.php
@extends('admin.layout.app')

@section('title')
إضافة  عقد بطاقات شحن
@endsection
@section('header')

@endsection

@section('content')

<!-- Basic Validation -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>إضافة  عقد بطاقات شحن</h2>
        <ul class="header-dropdown m-r--5">
            <a href="{{route('admin.card_contracts.index')}}">    <button class="btn btn-danger">كل عقود البطاقات </button></a>
        </ul>
      </div>
      <div class="body">
          {!!Form::open( ['route' => 'admin.card_contracts.store' ,'class'=>'form phone_validate', 'method' => 'Post','files' => true]) !!}
        @include('admin.card_contracts.form')
        {!!Form::close() !!}
      </div>
    </div>
  </div>
</div>
<!-- #END# Basic Validation -->
@endsection

resources/views/admin/card_contracts/edit.blade.php
@extends('admin.layout.app')
@section('title')
تعديل العقد
{{ $contract->id }}
@endsection
@section('header')

@endsection

@section('content')

<!-- Basic Validation -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>تعديل العقد      {{ $contract->id }}</h2>
        <ul class="header-dropdown m-r--5">
          <a href="{{route('admin.card_contracts.index')}}">    <button class="btn btn-danger">كل عقود بطاقات الشحن </button></a>
        </ul>
      </div>
      <div class="body">
        {!!Form::model($contract , ['route' => ['admin.card_contracts.update' , $contract->id] , 'method' => 'PATCH']) !!}
        @include('admin.card_contracts.form')
        {!!Form::close() !!}
      </div>
    </div>
  </div>
</div>


<!-- #END# Basic Validation -->
@endsection

@if(isset($guarantor))


@section('footer')
  <script>
    // Initialize and add the map
    function initMap() {
      // The location of Uluru
      var uluru = {lat: {{$user->lat}}, lng: {{$user->long}}};
      // The map, centered at Uluru
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: uluru
      });
      // The marker, positioned at Uluru
      var marker = new google.maps.Marker({
        position: uluru,
        map: map,
        draggable:true,
      });


      marker.addListener('drag', handleEvent);
      marker.addListener('dragend', handleEvent);
      document.getElementById('lat').value = {{$user->lat}};
      document.getElementById('lng').value = {{$user->long}};
    }

    function handleEvent(event) {
      document.getElementById('lat').value = event.latLng.lat();
      document.getElementById('lng').value = event.latLng.lng();
    }
  </script>


  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCsT140mx0UuES7ZwcfY28HuTUrTnDhxww&callback=initMap">
  </script>
@endsection


@endif

resources/views/admin/card_contracts/index.blade.php
@extends('admin.layout.app')

@section('title')
  عرض  بطاقات الشحن
@endsection
@section('header')
{{Html::style('admin/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}
<style>
  th.sorting, tr > td {
    display: table-cell!important;
  }


</style>
@endsection
@section('content')

<!-- Exportable Table -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>
          عرض  بطاقات الشحن
        </h2>
        <ul class="header-dropdown m-r--5">
          <a href="{{route('admin.card_contracts.create')}}">   <button class="btn btn-success">إضافة بطاقات شحن جديد</button></a>
</ul>
        </div>
        <div class="body">
          <table class="table table-bordered table-striped table-hover dataTable js-exportable">
            <thead>
              <tr>
                <th>#</th>
                <th>العميل</th>
                <th>الوسيط</th>
                <th> الضامن </th>
                <th>الفئه </th>
                <th>العدد </th>
                <th> اجمالى المبلغ  تسديده </th>

                <th> تاريخ بدء الاقساط </th>
                <th> المتبقى </th>
                <th>الاقساط </th>
                <th>تقرير </th>
                <th>السندات </th>

                <th>العمليات</th>
              </tr>
            </thead>
       <!--   <tfoot>
            <tr>
              <th>#</th>
              <th>العميل</th>
              <th>الوسيط</th>

              <th> الضامن </th>
              <th>الفئه </th>
              <th>العدد </th>
              <th> اجمالى المبلغ  تسديده </th>
              <th> تاريخ بدء الاقساط </th>
              <th> المتبقى </th>
              <th>الاقساط </th>
              <th>تقرير </th>
              <th>السندات </th>

              <th>العمليات</th>
            </tr>
          </tfoot>-->
          <tbody>
            @foreach($card_contracts as $key=>$contract)
            <tr>
              <td> {{++$key}}</td>
              <td>{{@$contract->client->name}}</td>
              <td>{{@$contract->mediator->name}}</td>
                @if ($contract->kind=="client")
                  <?php
                  $id=$contract->clientv2_id;
                  $client=\App\Client::find($id);
                  ?>
                  <td>{{optional($client)->name}}</td>
                @else
                  <?php
                  $id=$contract->guarantor_id;
                  $guarantor=\App\Guarantor::find($id);
                  ?>
                  <td>{{optional($guarantor)->name}}</td>
                @endif

              <td>{{$contract->class}}</td>
              <td>{{$contract->number}}</td>
              <td>{{($contract->class*$contract->number)+$contract->added_value}}</td>
              <td>{{$contract->start_date}}</td>

              <td>
                <?php
                $not_paid=\App\Payment::where('contract_id',$contract->id)->where('pay',0)->sum('one_pay');
                ?>
                {{round($not_paid)}}

              </td>


              <td>
                <a href="{{route('admin.card_contracts.show',['id'=>$contract->id])}}" class="btn btn-primary btn-circle"><i style="padding-top:5px;padding-left: 3px;" class="fa fa-list"></i></a>
                </td>
              <td>
                <a href="{{route('admin.card_contracts.report',['id'=>$contract->id])}}" class="btn btn-primary btn-circle"><i style="padding-top:5px;padding-left: 3px;" class="fa fa-eye"></i></a>
              </td>
              <td>
                <a href="{{route('admin.card_contracts.client_sanad',['id'=>$contract->id])}}" class="btn btn-success ">سند العميل</a>
                <a href="{{route('admin.card_contracts.guarantor_sanad',['id'=>$contract->id])}}" class="btn btn-success ">سند الكفيل</a>

              </td>
                <td>
                  <a href="{{route('admin.card_contracts.print',['id'=>$contract->id])}}" class="btn btn-primary btn-circle"><i style="padding-top:5px;padding-left: 3px;" class="fa fa-print"></i></a>
                  @if (Auth::user()->edit_contract==1)

                  <a href="{{route('admin.card_contracts.edit',['id'=>$contract->id])}}" class="btn btn-info btn-circle"><i style="padding-top:5px;padding-left: 3px;" class="fa fa-pencil"></i></a>
                @endif
                    @if (Auth::user()->delete_contract==1)
                <a href="#"  onclick="Delete({{$contract->id}})"  data-original-title="حذف" class="btn btn-danger btn-circle"><i style="padding-top: 5px;padding-left: 3px;" class="fa fa-trash-o"></i></a>
                {!!Form::open( ['route' => ['admin.card_contracts.destroy',$contract->id] ,'id'=>'delete-form'.$contract->id, 'method' => 'Delete']) !!}
                {!!Form::close() !!}
                    @endif
              </td>

            </tr>
            @endforeach

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- #END# Exportable Table -->

@endsection

@section('footer')
  <script>
    function Delete(id) {
      var item_id=id;
      console.log(item_id);
      swal({
        title: "هل أنت متأكد ",
        text: "هل تريد حذف هذا العقد ؟",
        icon: "warning",
        buttons: ["الغاء", "موافق"],
        dangerMode: true,

      }).then(function(isConfirm){
        if(isConfirm){
          document.getElementById('delete-form'+item_id).submit();
        }
        else{
          swal("تم االإلفاء", "حذف  المستخدم تم الغاؤه",'info',{buttons:'موافق'});
        }
      });
    }
  </script>

  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')!!}
  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/jszip.min.js')!!}
  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/pdfmake.min.js')!!}
  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/vfs_fonts.js')!!}
  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')!!}
  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/buttons.print.min.js')!!}
@endsection


@section('data-table')
   <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.18/r-2.2.2/datatables.min.js"></script>

    <script type="text/javascript"
            src="{{asset('admin/js/plugins/tables/datatables/datatables.min.js')}}"></script>
    <script type="text/javascript"
            src="{{asset('admin/js/plugins/tables/datatables/extensions/buttons.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/js/plugins/forms/selects/select2.min.js')}}"></script>
    <script type="text/javascript"
            src="{{asset('admin/js/plugins/datatables_extension_buttons_init.js')}}"></script>
@endsection

resources/views/admin/card_contracts/view.blade.php
@extends('admin.layout.app')

@section('title')
    عرض  الاقساط
@endsection
@section('header')
    {{Html::style('admin/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}
@endsection
@section('content')
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        عرض  الاقساط المتاخرة
                    </h2>


                </div>

                <div class="form-group form-float col-sm-6 col-xs-12">
                    <label >الاجمالى:
                        <label>
                            {{round($qests->sum('one_pay'),2)}}
                      </div>

                <div class="body">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable delet2">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th> اسم صاحب القسط</th>
                            <th> جوال صاحب القسط</th>
                            <th>تاريخ القسط</th>
                            <th>المبلغ المستحق </th>
                            <th>سداد </th>
                            <th> طباعه </th>

                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>#</th>
                            <th>تاريخ القسط</th>
                            <th>المبلغ المستحق </th>
                            <th>سداد </th>
                            <th> طباعه </th>
                        </tr>
                        </tfoot>
                        <tbody>
                        @foreach($qests as  $key=>$qest)
                            <tr>

                                <td>{{++$key}}</td>
                                <td>{{$qest->contract->client->name}}</td>
                                <td>{{$qest->contract->client->phone}}</td>

                                <td>{{$qest->date}}</td>
                                <td>{{ floor($qest->one_pay)}}</td>

                        @if ($qest->pay==0)

                                    <td>
                                        {{--<a href="{{route('admin.card_contracts.sadad',['id'=>$qest->id])}}" class="btn btn-primary btn-circle"><i style="padding-top:5px;padding-left: 6px;" class="fa fa-money"></i></a>--}}

                                        <a href="#"  onclick="myFunction({{$qest->id}})"  data-toggle="tooltip" class="btn btn-primary btn-circle" ><i style="padding-top:5px;padding-left: 6px;" class="fa fa-money"></i></a>
                                        {!!Form::open( ['route' => ['admin.card_contracts.sadad',$qest->id] ,'id'=>'reason-form'.$qest->id, 'method' => 'get']) !!}
                                        <input type="hidden" name="key" value="{{$key}}">

                                        {!!Form::close() !!}
                                    </td>
                            @else
                            <td> تم السداد</td>

                                @endif

                                <td>


                                    {{--<a href="{{route('admin.card_contracts.sadad_qests',['id'=>$qest->id])}}" class="btn btn-info btn-circle"><i style="padding-top:5px;padding-left: 6px;" class="fa fa-print"></i></a>--}}

                                    {!!Form::open( ['route' => ['admin.card_contracts.sadad_qests',$qest->id] , 'method' => 'post']) !!}
                                    <input type="hidden" name="key" value="{{$key}}">

                                    <button class="btn btn-info " type="submit"><i style="padding-top:5px;padding-left: 6px;" class="fa fa-print"></i></button>
                                    {!!Form::close() !!}


                                    {!!Form::open( ['route' => ['admin.car_contracts.sadad',$qest->id] ,'id'=>'reason-form'.$qest->id, 'method' => 'get']) !!}
                                    <input type="hidden" name="" value="{{$qest->one_pay}}" id="one_pay">
                                    {!!Form::close() !!}

                                </td>

                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->

@endsection

@section('footer')

    <script>
        function myFunction(id) {
            var item_id=id;
            var itemx= document.getElementById('one_pay');
            var value=  itemx.value;

            swal({


                title: "   سداد القسط",
                text: value +"هل  تريد سداد هذا القسط وقيمه المبلغ ؟",

                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function (isConfirm ) {
                if (isConfirm) {
                    console.log(item_id);
                    $('#ff').val($('#swal').val());
                    document.getElementById('reason-form'+item_id).submit();


                } else {
                    swal("تم االإلفاء", " سداد القسط  تم الغاؤه", 'info', {buttons: 'موافق'});
                }


            });


        }

    </script>
@endsection


@section('data-table')
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.18/r-2.2.2/datatables.min.js"></script>

    <script type="text/javascript"
            src="{{asset('admin/js/plugins/tables/datatables/datatables.min.js')}}"></script>
    <script type="text/javascript"
            src="{{asset('admin/js/plugins/tables/datatables/extensions/buttons.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/js/plugins/forms/selects/select2.min.js')}}"></script>
<!--     <script type="text/javascript"
            src="{{asset('admin/js/plugins/datatables_extension_buttons_init.js')}}"></script> -->
        <script>
            $(function () {



            $.extend($.fn.dataTable.defaults, {
                autoWidth: false,
                dom: '<"datatable-header"fBl><"datatable-scroll-wrap"t><"datatable-footer"ip>',
                language: {
                    search: '<span>Filter:</span> _INPUT_',
                    searchPlaceholder: 'Type to filter...',
                    lengthMenu: '<span>Show:</span> _MENU_',
                    paginate: {'first': 'First', 'last': 'Last', 'next': '&larr;', 'previous': '&rarr;'}
                }
            });
            // Basic initialization
            $('table.js-exportable').DataTable({
                responsive: true,
                buttons: {
                    dom: {
                        button: {
                            className: 'btn btn-default'
                        }
                    },
                    buttons: [
                        {extend: 'copy'},
                        {extend: 'csv'},
                        {extend: 'excel'},
                        {extend: 'pdf'},
                        {extend: 'print' ,
                        title:"الاقساط المتأخرة",
                        customize: function ( win ) {
                                $(win.document.body)
                                    .css( 'font-size', '10pt' )
                                    .append(
                                        ` <div class="form-group divcustomesize">
                                <label >اجمالي مبالغ الاقساط:
                                    <label>
                                        {{round($qests->sum('one_pay'),2)}}
                                </div>`
                                    );


                            }
                    }
                    ]
                }
            });
            });
        </script>
@endsection