routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.layout.login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(array('prefix' => 'dashboard','as'=>'admin.' ,'middleware' => 'auth'), function() {

    Route::get('/', 'indexController@index')->name('layout.main');

    Route::resource('users', 'userController');
    Route::resource('guarantors', 'guarantorController');
    Route::resource('clients', 'clientController');
    Route::resource('mediators', 'mediatorController');
    Route::resource('settings', 'settingController');

    Route::resource('clearances', 'clearanceController');
    Route::resource('car_contracts', 'car_contractController');
    Route::resource('card_contracts', 'card_contractController');
    Route::any('/card_sadad/{id}','card_contractController@sadad' )->name('card_contracts.sadad');

    Route::post('/sadad-qests/{id}','card_contractController@qest_sadad' )->name('card_contracts.sadad_qests');
    Route::any('/sadad-cars/{id}','car_contractController@qest_sadad' )->name('car_contracts.sadad_qests');


    Route::get('/card','card_contractController@qast' )->name('card_contracts.qests');

    Route::get('/sadad/{id}','car_contractController@sadad' )->name('car_contracts.sadad');
    Route::get('/card_report/{id}','card_contractController@report' )->name('card_contracts.report');

    Route::get('/report/{id}','car_contractController@report' )->name('car_contracts.report');
    Route::get('/contract/{id}','car_contractController@print' )->name('car_contracts.print');
    Route::get('/card_contract/{id}','card_contractController@print' )->name('card_contracts.print');

    Route::get('/client_sanad/{id}','car_contractController@client_sanad' )->name('car_contracts.client_sanad');
    Route::get('/guarantor_sanad/{id}','car_contractController@guarantor_sanad' )->name('car_contracts.guarantor_sanad');

    Route::get('/card_client_sanad/{id}','card_contractController@client_sanad' )->name('card_contracts.client_sanad');
    Route::get('/card_guarantor_sanad/{id}','card_contractController@guarantor_sanad' )->name('card_contracts.guarantor_sanad');
    Route::any('/collected_premiums','ReportController@premiums')->name('reports.collected_premiums');

});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Attribute
 *
 * @property int $id
 * @property string $ar_name
 * @property string $en_name
 * @property string $type
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Attribute_value[] $attribute_values
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Attribute newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Attribute newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Attribute query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Attribute whereArName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Attribute whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Attribute whereEnName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Attribute whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Attribute whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Attribute whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property int $branch_id
 * @property string|null $deleted_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Product[] $products
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Attribute whereBranchId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Attribute whereDeletedAt($value)
 */
class Client extends Model
{
    protected $fillable = ['name', 'national_id', 'date','origin','guarantor_id','phone','address','job'];
    public function guarantor()
    {
        return $this->belongsTo(Guarantor::class);
    }
    public function clearance()
    {
        return $this->hasMany(Clearance::class);
    }

    public function contract()
    {
        return $this->hasMany(Contract::class);
    }
}

app/Http/Controllers/clientController.php
<?php

namespace App\Http\Controllers;

use App\Activity;
use App\City;
use App\Client;
use App\Contract;
use App\Guarantor;
use App\User;
use function GuzzleHttp\Promise\all;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Hash;

class clientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.clients.index')->with('clients',Client::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $guarantors=Guarantor::pluck('name','id')->toArray();
        return view('admin.clients.add',compact('guarantors'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       //dd($request->all());
        $this->validate($request,[
            'name'=>'required|string|',
            'national_id'=>'required|string|',
            'origin'=>'required|string|',


        ]);
        $inputs=$request->all();

       $client= Client::create($inputs);
        $text=' اضافه العميل '. $client->name;
        Activity($text);

        alert()->success('تم اضافة العميل بنجاح !')->autoclose(5000);
        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $contracts=Contract::where('client_id',$id)->get();
        return view('admin.clients.view',compact('contracts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $client=Client::find($id);
        $guarantors=Guarantor::pluck('name','id')->toArray();
        return view('admin.clients.edit',compact('client','guarantors'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $client=Client::find($id);
        $this->validate($request,[
            'name'=>'required|string|',
            'national_id'=>'required|string|',
            'origin'=>'required|string|',
        ]);
        $inputs=$request->all();
        $client->update($inputs);
        $text=' تعديل العميل '. $client->name;
        Activity($text);
        alert()->success('تم تعديل  العميل بنجاح !')->autoclose(5000);
        return redirect('dashboard/clients');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    { //dd($id);

        $client=Client::find($id);


            $client->delete();
        $text=' حذف العميل '. $client->name;
        Activity($text);
            alert()->success('تم حذف العميل  بنجاح');
            return back();

    }
}

resources/views/admin/clients/add.blade.php
@extends('admin.layout.app')

@section('title')
إضافة  عميل
@endsection
@section('header')

@endsection

@section('content')

<!-- Basic Validation -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>إضافة عميل </h2>
        <ul class="header-dropdown m-r--5">
            <a href="{{route('admin.clients.index')}}">    <button class="btn btn-danger">كل العملاء </button></a>
        </ul>
      </div>
      <div class="body">
          {!!Form::open( ['route' => 'admin.clients.store' ,'class'=>'form phone_validate', 'method' => 'Post','files' => true]) !!}
        @include('admin.clients.form')
        {!!Form::close() !!}
      </div>
    </div>
  </div>
</div>
<!-- #END# Basic Validation -->
@endsection

resources/views/admin/clients/edit.blade.php
@extends('admin.layout.app')
@section('title')
تعديل العميل
{{ $client->name }}
@endsection
@section('header')

@endsection

@section('content')

<!-- Basic Validation -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>تعديل العميل      {{ $client->name }}</h2>
        <ul class="header-dropdown m-r--5">
          <a href="{{route('admin.clients.index')}}">    <button class="btn btn-danger">كل العملاء </button></a>
        </ul>
      </div>
      <div class="body">
        {!!Form::model($client , ['route' => ['admin.clients.update' , $client->id] , 'method' => 'PATCH']) !!}
        @include('admin.clients.form')
        {!!Form::close() !!}
      </div>
    </div>
  </div>
</div>


<!-- #END# Basic Validation -->
@endsection

resources/views/admin/clients/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<input type="hidden" name="id" value="@isset($user) {!! $user->id !!} @endisset">
<div class="col-sm-6 col-xs-12  pull-right">
    <div class="form-group form-float">
  <label class="form-label">الإسم</label>
  <div class="form-line">
    {!! Form::text("name",null,['class'=>'form-control','placeholder'=>'  الاسم  '])!!}
  </div>
</div>
</div>


<div class="col-sm-6 col-xs-12  pull-right">
<div class="form-group form-float">
    <label > رقم الهوية</label>
    <div class="form-line">
            {!! Form::text("national_id",null,['class'=>'form-control','placeholder'=>'  رقم الهويه  '])!!}

    </div>
</div>
</div>

<div class="col-sm-6 col-xs-12  pull-right">
    <div class="form-group form-float">
        <label > جهة صدورها</label>
       
        <div class="form-line">
             {!! Form::text("origin",null,['class'=>'form-control','placeholder'=>'  جهة الصدور  '])!!}
        </div>
    </div>
</div>

<div class="col-sm-6 col-xs-12  pull-right">
    <div class="form-group form-float">
        <label> تاريخ الاصدار</label>
        {{--<input type="text" name="date" class=" form-control datepicker-hijri_1">--}}

        <div class="form-line">
                    {!! Form::text("date",null,['class'=>'form-control datepicker-hijri_1'])!!}

        </div>
    </div>
</div>

<div class="col-sm-6 col-xs-12  pull-right">
    <div class="form-group form-float">
        <label >الجوال</label>
        <div class="form-line">
                    {!! Form::text("phone",null,['class'=>'form-control','placeholder'=>'الجوال  '])!!}

        </div>
    </div>
</div>


<div class="col-sm-6 col-xs-12  pull-right">
    <div class="form-group form-float">
        <label >العنوان</label>
        <div class="form-line">
                    {!! Form::text("address",null,['class'=>'form-control ','placeholder'=>'العنوان  '])!!}

        </div>
    </div>
</div>


<div class="col-sm-6 col-xs-12  pull-right">
    <div class="form-group form-float">
        <label >  الوظيفة</label>
        <div class="form-line">
                    {!! Form::text("job",null,['class'=>'form-control','placeholder'=>'  الوظيفه  '])!!}

        </div>
    </div>
</div>
<div class="col-sm-6 col-xs-12  pull-right">
<div class="form-group form-float">
    <label class="form-label" >الكفيل </label>
    {!! Form::select("guarantor_id",$guarantors,null,['class'=>'form-control js-example-basic-single','placeholder'=>'اختر الكفيل   '])!!}
</div>
</div>










<div class="col-xs-12">
    <button class="btn btn-primary waves-effect" type="submit">حفظ</button>
</div>



@section('footer')



    <script type="text/javascript" src="{{asset('/admin/hijri-calender/js/jquery.calendars.js')}}"></script>

    <script type="text/javascript" src="{{asset('/admin/hijri-calender/js/jquery.calendars.plus.js')}}"></script>
    <script type="text/javascript" src="{{asset('/admin/hijri-calender/js/jquery.plugin.js')}}"></script>
    <script type="text/javascript" src="{{asset('/admin/hijri-calender/js/jquery.calendars.picker.js')}}"></script>

    <script type="text/javascript" src="{{asset('/admin/hijri-calender/js/jquery.calendars.ummalqura.js')}}"></script>
    <script>
        (function ($) {
            $.calendars.calendars.ummalqura.prototype.regionalOptions['ar'] = {
                name: 'Islamic',
                epochs: ['BAM', 'AM'],
                monthNames: ['محرّم', 'صفر', 'ربيع الأول', 'ربيع الآخر أو ربيع الثاني', 'جمادى الاول', 'جمادى الآخر أو جمادى الثاني',
                    'رجب', 'شعبان', 'رمضان', 'شوّال', 'ذو القعدة', 'ذو الحجة'],
                monthNamesShort: ['محرّم', 'صفر', 'ربيع الأول', 'ربيع الآخر أو ربيع الثاني', 'جمادى الاول', 'جمادى الآخر أو جمادى الثاني',
                    'رجب', 'شعبان', 'رمضان', 'شوّال', 'ذو القعدة', 'ذو الحجة'],
                dayNames: ['اح', 'اث', 'ث', 'ار', 'خ', 'ج', 'س'],
                dayNamesShort: ['اح', 'اث', 'ث', 'ار', 'خ', 'ج', 'س'],
                dayNamesMin: ['اح', 'اث', 'ث', 'ار', 'خ', 'ج', 'س'],
                digits: $.calendars.substituteDigits(['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩']),
                dateFormat: 'yyyy-mm-dd',
                firstDay: 6,
                isRTL: true
            };
        })(jQuery);
        $(function () {

            var calendar = $.calendars.instance('ummalqura', 'ar');
            $('.datepicker-hijri_1').calendarsPicker({
                calendar: calendar,
                defaultDate: '-1d',

                onSelect: function (date) {
                    var selectHijriDate = date[0];
                    //  convertToGeorgian(selectHijriDate.toString(),"national_id_date"); // ajax request

                }
            });


        });
    </script>





@endsection

resources/views/admin/clients/index.blade.php
@extends('admin.layout.app')

@section('title')
  عرض  العملاء
@endsection
@section('header')
  {{Html::style('admin/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}
@endsection
@section('content')
  <!-- Exportable Table -->
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>
            عرض  العملاء
          </h2>
          <ul class="header-dropdown m-r--5">
            <a href="{{route('admin.clients.create')}}">   <button class="btn btn-success">إضافة عميل جديد</button></a>
          </ul>
        </div>
        <div class="body">
          <table class="table table-bordered table-striped table-hover dataTable js-exportable">
            <thead>
            <tr>
              <th>الإسم</th>
              <th>رقم الهويه</th>
              <th> جهه الصدور</th>
              <th>تاريخ الصدور</th>
              <th> الوظيفة</th>
              <th> العنوان</th>
              <th>اسم الكفيل</th>
              <th> العقود</th>
              <th>العمليات</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
              <th>الإسم</th>
              <th>رقم الهويه</th>
              <th> جهه الصدور</th>
              <th>تاريخ الصدور</th>
              <th> الوظيفة</th>
              <th> العنوان</th>
              <th>اسم الكفيل</th>
              <th> العقود</th>

              <th>العمليات</th>
            </tr>
            </tfoot>
            <tbody>
            @foreach($clients as $client)
              <tr>
                <td>{{$client->name}}</td>
                <td>{{$client->national_id}}</td>
                <td>{{$client->origin}}</td>
                <td>{{$client->date}}</td>
                <td>{{$client->job}}</td>
                <td>{{$client->address}}</td>

                <td>
                  @if (isset($client->guarantor_id))
                    {{$client->guarantor->name}}
                  @endif
                  ----
                </td>

                <td>
                  <a href="{{route('admin.clients.show',['id'=>$client->id])}}" class="btn btn-primary btn-circle"><i style="padding-top:5px;padding-left: 6px;" class="fa fa-money"></i></a>
                </td>
                <td>
                  <a href="{{route('admin.clients.edit',['id'=>$client->id])}}" class="btn btn-info btn-circle"><i style="padding-top:5px;padding-left: 6px;" class="fa fa-pencil"></i></a>
                 @if (Auth::user()->delete_client==1)
                    <a href="#"  onclick="Delete({{$client->id}})"  data-original-title="حذف" class="btn btn-danger btn-circle"><i style="padding-top: 5px;padding-left: 4px;" class="fa fa-trash-o"></i></a>
                    {!!Form::open( ['route' => ['admin.clients.destroy',$client->id] ,'id'=>'delete-form'.$client->id, 'method' => 'Delete']) !!}
                    {!!Form::close() !!}
                 @endif


                </td>

              </tr>
            @endforeach

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- #END# Exportable Table -->

@endsection

@section('footer')
  <script>
    function Delete(id) {
      var item_id=id;
      console.log(item_id);
      swal({
        title: "هل أنت متأكد ",
        text: "هل تريد حذف هذا العميل ؟",
        icon: "warning",
        buttons: ["الغاء", "موافق"],
        dangerMode: true,

      }).then(function(isConfirm){
        if(isConfirm){
          document.getElementById('delete-form'+item_id).submit();
        }
        else{
          swal("تم االإلفاء", "حذف  المستخدم تم الغاؤه",'info',{buttons:'موافق'});
        }
      });
    }
  </script>
  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')!!}
  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/jszip.min.js')!!}
  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/pdfmake.min.js')!!}
  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/vfs_fonts.js')!!}
  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')!!}
  {!!Html::script('admin/plugins/jquery-datatable/extensions/export/buttons.print.min.js')!!}
@endsection


@section('data-table')
  <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.18/r-2.2.2/datatables.min.js"></script>

  <script type="text/javascript"
          src="{{asset('admin/js/plugins/tables/datatables/datatables.min.js')}}"></script>
  <script type="text/javascript"
          src="{{asset('admin/js/plugins/tables/datatables/extensions/buttons.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('admin/js/plugins/forms/selects/select2.min.js')}}"></script>
  <script type="text/javascript"
          src="{{asset('admin/js/plugins/datatables_extension_buttons_init.js')}}"></script>
@endsection

resources/views/admin/clients/view.blade.php
@extends('admin.layout.app')

@section('title')
  عرض  بطاقات الشحن
@endsection
@section('header')
  {{Html::style('admin/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}
@endsection
@section('content')
  <!-- Exportable Table -->
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>
            عرض  بطاقات الشحن
          </h2>
          <ul class="header-dropdown m-r--5">
            <a href="{{route('admin.card_contracts.create')}}">   <button class="btn btn-success">إضافة بطاقات شحن جديد</button></a>
          </ul>
        </div>
        <div class="body">
          <table class="table table-bordered table-striped table-hover dataTable js-exportable">
            <thead>
            <tr>
              <th>#</th>
              <th>العميل</th>
              <th>نوع العقد</th>

              <th> تاريخ بدء الاقساط </th>
              <th>المبلغ </th>
              <th>القيمه المضافة </th>

            </tr>
            </thead>
            <tfoot>
            <tr>
              <th>#</th>
              <th>العميل</th>
              <th>نوع العقد</th>

              <th> تاريخ بدء الاقساط </th>
              <th>المبلغ </th>
              <th>القيمه المضافة </th>


            </tr>
            </tfoot>
            <tbody>
            @foreach($contracts as $key=>$contract)
              <tr>
                <td> {{++$key}}</td>
                <td>{{$contract->client->name}}</td>


                  @if ($contract->type=="car")
                  <td> عقد سيارات </td>
                    @else
                  <td>  عقد بطاقات شحن</td>
                  @endif



                <td>{{$contract->start_date}}</td>

                <td>{{$contract->amount}}</td>
                <td>{{$contract->added_value}}</td>

              </tr>
            @endforeach

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- #END# Exportable Table -->

@endsection

@section('footer')
  <script>
    function Delete(id) {
      var item_id=id;
      console.log(item_id);
      swal({
        title: "هل أنت متأكد ",
        text: "هل تريد حذف هذا المستخدم ؟",
        icon: "warning",
        buttons: ["الغاء", "موافق"],
        dangerMode: true,

      }).then(function(isConfirm){
        if(isConfirm){
          document.getElementById('delete-form'+item_id).submit();
        }
        else{
          swal("تم االإلفاء", "حذف  المستخدم تم الغاؤه",'info',{buttons:'موافق'});
        }
      });
    }
  </script>
@endsection


@section('data-table')
  <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.18/r-2.2.2/datatables.min.js"></script>

  <script type="text/javascript"
          src="{{asset('admin/js/plugins/tables/datatables/datatables.min.js')}}"></script>
  <script type="text/javascript"
          src="{{asset('admin/js/plugins/tables/datatables/extensions/buttons.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('admin/js/plugins/forms/selects/select2.min.js')}}"></script>
  <script type="text/javascript"
          src="{{asset('admin/js/plugins/datatables_extension_buttons_init.js')}}"></script>
@endsection