routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.layout.login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(array('prefix' => 'dashboard','as'=>'admin.' ,'middleware' => 'auth'), function() {

    Route::get('/', 'indexController@index')->name('layout.main');

    Route::resource('users', 'userController');
    Route::resource('guarantors', 'guarantorController');
    Route::resource('clients', 'clientController');
    Route::resource('mediators', 'mediatorController');
    Route::resource('settings', 'settingController');

    Route::resource('clearances', 'clearanceController');
    Route::resource('car_contracts', 'car_contractController');
    Route::resource('card_contracts', 'card_contractController');
    Route::any('/card_sadad/{id}','card_contractController@sadad' )->name('card_contracts.sadad');

    Route::post('/sadad-qests/{id}','card_contractController@qest_sadad' )->name('card_contracts.sadad_qests');
    Route::any('/sadad-cars/{id}','car_contractController@qest_sadad' )->name('car_contracts.sadad_qests');


    Route::get('/card','card_contractController@qast' )->name('card_contracts.qests');

    Route::get('/sadad/{id}','car_contractController@sadad' )->name('car_contracts.sadad');
    Route::get('/card_report/{id}','card_contractController@report' )->name('card_contracts.report');

    Route::get('/report/{id}','car_contractController@report' )->name('car_contracts.report');
    Route::get('/contract/{id}','car_contractController@print' )->name('car_contracts.print');
    Route::get('/card_contract/{id}','card_contractController@print' )->name('card_contracts.print');

    Route::get('/client_sanad/{id}','car_contractController@client_sanad' )->name('car_contracts.client_sanad');
    Route::get('/guarantor_sanad/{id}','car_contractController@guarantor_sanad' )->name('car_contracts.guarantor_sanad');

    Route::get('/card_client_sanad/{id}','card_contractController@client_sanad' )->name('card_contracts.client_sanad');
    Route::get('/card_guarantor_sanad/{id}','card_contractController@guarantor_sanad' )->name('card_contracts.guarantor_sanad');
    Route::any('/collected_premiums','ReportController@premiums')->name('reports.collected_premiums');

});

app/Http/Controllers/car_contractController.php
<?php

namespace App\Http\Controllers;

use App\Activity;
use App\City;
use App\Client;
use App\CollectPremium;
use App\Contract;
use App\Guarantor;
use App\Http\Helpers\num_to_ar;
use App\Mediator;
use App\Payment;
use App\User;
use function GuzzleHttp\Promise\all;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Hash;

use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use GeniusTS\HijriDate\Date;

class car_contractController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {




        return view('admin.car_contracts.index')->with('car_contracts',Contract::where('type','car')->orderByDesc('created_at')->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients=Client::pluck('name','id')->toArray();
        $mediators=Mediator::pluck('name','id')->toArray();
        $guarantors=Guarantor::pluck('name','id')->toArray();

        return view('admin.car_contracts.add',compact('guarantors','mediators','clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[



        ]);

        $inputs=$request->all();
        $user_id=Auth::user()->id;
        $contract= Contract::create($inputs);
        $client_id=$inputs['client_id'];
        $start_date=$inputs['start_date'];

        $added_value=$inputs['added_value'];
        $months_count=$inputs['months_count'];
        $paid_amount=$inputs['paid_amount'];

        $amount=$inputs['amount'];
        $total_amount=$amount+$added_value;
        $onepay=($total_amount)/$months_count;

        $contract->update([
            'type'=>'car',
            'amount'=>$amount
        ]);


        for ($i=0;$i<$months_count;$i++)

        {
            Payment::create([
                'user_id'=>$user_id,
                'client_id'=>$client_id,
                'contract_id'=>$contract->id,
                'one_pay'=>$onepay,
                'amount'=>$total_amount,
                'date'=>$start_date
            ]);
            $total_amount=$total_amount-$onepay;
            $start_date=Carbon::parse($start_date)->addMonths(1);

        }
        $text=' اضافه عقد  سيارات '. $contract->id;
        Activity($text);

//        alert()->success('تم اضافة العقد بنجاح !')->autoclose(5000);
//        return back();



        $numbers=new num_to_ar($contract->paid_amount,"male");
        $total=$numbers->convert_number().' '.'ريال';


        $allnum=new num_to_ar($contract->amount+$contract->added_value+$contract->paid_amount,"male");
        $total_all=$allnum->convert_number().' '.'ريال';


        $contract_date1= $contract->created_at;

        $today_date = $contract_date1->format('d-m-Y');
        $payment=Payment::where('contract_id',$contract->id)->first();

        $numbersx=new num_to_ar(floor($payment->one_pay),"male");
        $one_pay=$numbersx->convert_number().' '.'ريال';

        $date = \GeniusTS\HijriDate\Hijri::convertToHijri($today_date)->format('d-m-Y');
        $day = $contract_date1->format('D');
        //    dd($payment);
        if ($day=='Sat') {
            $dayname = 'السبت';
        }else  if ($day=='Sun') {
            $dayname = 'الاحد';
        }else  if ($day=='Mon') {
            $dayname = 'الاثنين';
        }else  if ($day=='Tue') {
            $dayname = 'الثلاتاء';
        }else  if ($day=='Wed') {
            $dayname = 'الاربعاء';
        }else  if ($day=='Thu') {
            $dayname = 'الخميس';
        }else  if ($day=='Fri') {
            $dayname = 'الجمعة';
        }


        return view('admin.car_contracts.contract',compact('total_all','contract','total','one_pay','today_date','date','payment','dayname','payment'));




    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $qests=Payment::where('contract_id',$id)->get();
     //  dd($qests);
        return view('admin.car_contracts.view',compact('qests'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $contract=Contract::find($id);

        $clients=Client::pluck('name','id')->toArray();
        $mediators=Mediator::pluck('name','id')->toArray();
        $guarantors=Guarantor::pluck('name','id')->toArray();
        return view('admin.car_contracts.edit',compact('contract','guarantors','clients','mediators'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $contract=Contract::find($id);
        $this->validate($request,[

        ]);
        $inputs=$request->all();
        $contract->update($inputs);

        $text=' تعديل العقد '. $contract->id;
        Activity($text);
        alert()->success('تم تعديل  العقد بنجاح !')->autoclose(5000);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $contract=Contract::find($id);


        $contract->delete();
        $text=' حذف العقد '. $contract->id;
        Activity($text);
        alert()->success('تم حذف العقد بنجاح');
        return back();

    }
    public function sadad(Request $request,$id)
    {
        $payment=Payment::find($id);
        $payment->update([
            'pay'=>1,
            'updated_at'=>Date::today()->format('d-m-Y')


        ]);
        $qests=Payment::where('contract_id',$id)->get();

        CollectPremium::create([
            'date'=>Date::today()->format('Y-m-d'),
            'payment_id'=>$payment->id,
            'amount'=>$payment->amount,
        ]);
//        return back();

        $qest_num=$request['key'];
        return view('admin.car_contracts.sadad',compact('payment','qest_num'));

    }


    public function report($id)
    {

        $contract=Contract::find($id);
        $paymemts_paid=Payment::where('contract_id',$id)->where('pay',1)->count();
        $paymemts_notpaid=Payment::where('contract_id',$id)->where('pay',0)->count();
        $payments=Payment::where('contract_id',$id)->where('pay',0)->get();
        $paid=Payment::where('contract_id',$id)->where('pay',1)->sum('one_pay');
        $not_paid=Payment::where('contract_id',$id)->where('pay',0)->sum('one_pay');
        $ss=ceil($not_paid);

        return view('admin.car_contracts.report',compact('contract','paymemts_paid','paymemts_notpaid','payments','paid','not_paid','ss'));

    }
    public function print($id){

        $contract=Contract::find($id);

        $numbers=new num_to_ar($contract->paid_amount,"male");
        $total=$numbers->convert_number().' '.'ريال';


        $allnum=new num_to_ar($contract->amount+$contract->added_value+$contract->paid_amount,"male");
        $total_all=$allnum->convert_number().' '.'ريال';


        $contract_date1= $contract->created_at;

        $today_date = $contract_date1->format('d-m-Y');
       $payment=Payment::where('contract_id',$contract->id)->first();

        $numbersx=new num_to_ar(floor($payment->one_pay),"male");
        $one_pay=$numbersx->convert_number().' '.'ريال';

        $date = \GeniusTS\HijriDate\Hijri::convertToHijri($today_date)->format('d-m-Y');
        $day = $contract_date1->format('D');
    //    dd($payment);
        if ($day=='Sat') {
            $dayname = 'السبت';
        }else  if ($day=='Sun') {
            $dayname = 'الاحد';
        }else  if ($day=='Mon') {
            $dayname = 'الاثنين';
        }else  if ($day=='Tue') {
            $dayname = 'الثلاتاء';
        }else  if ($day=='Wed') {
            $dayname = 'الاربعاء';
        }else  if ($day=='Thu') {
            $dayname = 'الخميس';
        }else  if ($day=='Fri') {
            $dayname = 'الجمعة';
        }


        return view('admin.car_contracts.contract',compact('total_all','contract','total','one_pay','today_date','date','payment','dayname','payment'));
    }




    public function qest_sadad(Request $request,$id){

        $payment=Payment::find($id);
        $qest_num=$request['key'];
        return view('admin.car_contracts.sadad',compact('payment','qest_num'));
    }
    public  function guarantor_sanad($id){

        $contract=Contract::find($id);
        $numbers=new num_to_ar($contract->amount+$contract->added_value+$contract->paid_amount,"male");
        $total=$numbers->convert_number().' '.'ريال';

        $contract_date1= $contract->created_at;

        $today_date = $contract_date1->format('d-m-Y');
        $payment=Payment::where('contract_id',$contract->id)->first();

        $numbersx=new num_to_ar($payment->one_pay,"male");
        $one_pay=$numbersx->convert_number()." ".'ريال';

        $date = \GeniusTS\HijriDate\Hijri::convertToHijri($today_date)->format('d-m-Y');
        $day = $contract_date1->format('D');
        //    dd($payment);
        if ($day=='Sta') {
            $dayname = 'السبت';
        }else  if ($day=='Sun') {
            $dayname = 'الاحد';
        }else  if ($day=='Mon') {
            $dayname = 'الاثنين';
        }else  if ($day=='Tue') {
            $dayname = 'الثلاتاء';
        }else  if ($day=='Wen') {
            $dayname = 'الاربعاء';
        }else  if ($day=='Thr') {
            $dayname = 'الخميس';
        }else  if ($day=='Fri') {
            $dayname = 'الجمعة';
        }

resources/views/admin/car_contracts/add.blade.php
@extends('admin.layout.app')

@section('title')
إضافة  عقد سياره
@endsection
@section('header')

@endsection

@section('content')

<!-- Basic Validation -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>اضافه عقد سيارة</h2>
        <ul class="header-dropdown m-r--5">
            <a href="{{route('admin.car_contracts.index')}}">    <button class="btn btn-danger">عقود السيارات </button></a>
        </ul>
      </div>
      <div class="body">
          {!!Form::open( ['route' => 'admin.car_contracts.store' ,'class'=>'form phone_validate', 'method' => 'Post','files' => true]) !!}
        @include('admin.car_contracts.form')
        {!!Form::close() !!}
      </div>
    </div>
  </div>
</div>
<!-- #END# Basic Validation -->
@endsection

resources/views/admin/car_contracts/client_sanad.blade.php
<?php
if ($contract->kind=="client")
{
    $id=$contract->clientv2_id;

    $secound=\App\Client::find($id);

}
else
{
    $id=$contract->guarantor_id;
    $secound=\App\Guarantor::find($id);

}



$months_count=$contract->months_count;
$start_date=$contract->start_date;

$end_date=\Carbon\Carbon::parse($start_date)->addMonths($months_count-1);
$end=$end_date->format('d/m/Y');


?>
<!DOCTYPE html>
<html lang="en">
   <head>
      <title>سند لأمر</title>
      <link rel="stylesheet" href="css/bootstrap.min.css">
   </head>
   <style>
      body {
      width: 100%;
      height: 100%;
      margin: 0;
      padding: 0;
      background-color: #FAFAFA;
      font: 12pt "Tahoma";
      direction: rtl;
      }
      * {
      box-sizing: border-box;
      -moz-box-sizing: border-box;
      }
      .height-modifay{
          height: 90px;
      }
      .page {
      width: 210mm;
      min-height: 297mm;
      padding: 10mm 0mm;
      margin: 5mm;
      border: 10px #f00 solid;
      border-radius: 5px;
      background: white;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
      }
      .subpage {
      padding: 0.5cm;
      border: 5px black solid;
      height: 282mm;
      outline: 0cm;
      }
      .subpage h2 {
      text-align: center;
      width: 100%;
      display: inline-block
      }
      /**  /////////////////////////////  REEM ////////////////////////////////////// */
      .head {
      border-bottom: 2px black solid;
      display: flex;
      }
      .logo {
      width: 80px;
      height: 80px;
      object-fit: contain;
      }
      .content-top {
      display: flex;
      }
      .date {
      font-weight: bold;
      }
      .right {
      width: 50%;
      }
      .p-right-width {
      width: 220px;
      line-height: 1.8;
      height: 60px;
      text-align: center;
      }
      .left {
      width: 50%;
      }
      .left {
      text-align: left;
      }
      .p-left {
      text-align: left;
      }
      .p-inline {
      display: inline-block;
      }
      .p-width {
      min-width: 50%;
      float: left;
      }
      .content {
      margin-top: 20px;
      }
      .date {
      width: 50px;
      display: inline-block;
          color: #b33133;
      }
      .text-center {
      text-align: center;
      margin: 0 auto;
      }
       .content h3{
           border-bottom: 1px solid;
           width: max-content;
       }


      /********* MODIFICATIONS ************/
      .content-top .left {
          text-align: center !important;
      }
      .spann {
          min-width: 50px !important;
      }
      span.dates.long {
          width: auto !important;
          display: inline-block !important;
          margin: 0 !important;
      }

      .date {
          min-width: 20px !important;
          width: auto !important;
      }
      /************************/
       p {
    line-height: 1.5;
}
       .btm{
           width: 100%;
           min-height: 30px;
           display: block;
       }
      .bold {
      font-weight: bold;
      }
      .foot {
      margin-top: 30px;
          color: #b33133;
      }
      .spann {
      display: inline-block;
      min-width: 150px;
      text-align: center;
          color: #b33133;
      }
      .width-right {
      width: 62px !important;
      text-align: right;
      display: inline-block;
      font-weight: bold;
      }
      .margin {
      margin: 30px auto 10px auto;
      }
       .long{
           width: 100%;
           display: block;
           margin: 10px 0 0 0;
       }
       .sml{
           min-width: 50px;
       }
      /* Table */
      table,
      td,
      th {
      border: 1px solid black;
      text-align: center;
      }
      table {
      border-collapse: collapse;
      width: 100%;
          margin: 20px auto 0 auto;
      }
      th,
      td {
      height: 40px;
      }
       td{
           color: #b33133;
       }
       th {
           width: 160px;
       }
      @page {
      size: A4;
      margin: 0;
      }
      @media print {
      html,
      body {
      width: 210mm;
      height: 297mm;
      }
      .page {
      margin: 0;
      border: initial;
      border-radius: initial;
      width: initial;
      min-height: initial;
      box-shadow: initial;
      background: initial;
      page-break-after: always;
      }
      }
   </style>
   <body>
      <div class="book">
         <div class="page">
            <div class="subpage">
               <div class="content">
                   <h3 class="text-center bold">سند لأمر</h3>
                  <div class="content-top">
                     <div class="right">
                        <p> <span class="bold">حرر بمدينة:-</span> <span> بريدة </span> </p>
                     </div>
                     <div class="left">
                         <span class="bold" >رقم السند:{{$contract->id}}</span><br>
                        <span class="bold"> بتاريخ :-</span>
                        <span class="dates">
                        {{$date}}
                         </span> هـ
                     </div>
                  </div>
                  <p>
                     <span class="bold"> الموافق :-</span>
                        <span class="dates">
                                  {{$today_date}}

                        </span> م
                  </p>
                  <p>
                     <span class="bold">أتعهد أنا المدعو أدناه بأن أدفع بموجب هذا السند بدون قيد أو شرط لأمر / :-</span> <span class="btm">  عبد الرحمن رجاء العنزي </span>
                  </p>
                   <p>
                    مبلغا وقدره ( <span class="spann">{{$contract->amount+$contract->added_value+$contract->paid_amount}}</span> ) ريال <span class="spann">{{$total}} </span> فقط لا غير بتاريخ الاستحقاق
                       <span class="dates long">{{$end}}
                        </span> م
                   </p>
                   <p>
                        هذا السند واجب الدفع بدون تعلل بموجب قرار مجلس الوزراء الموقر رقم ( <span class="spann sml">692</span> ) وبتاريخ
                       <span class="dates">
                        <span class="date text-center"> 26</span>/
                        <span class="date text-center">09</span>/
                        <span class="date text-center">1383</span>
                        </span> هـ
                       والمتوج بالمرسوم الملكى الكريم رقم ( <span class="spann sml">37</span> ) بتاريخ
                       <span class="dates">
                        <span class="date text-center">11</span>/
                        <span class="date text-center">10</span>/
                        <span class="date text-center">1383</span>
                        </span> هـ
                       نظام الأوراق التجارية .
                   </p>
                   <p>
                    بموجب هذا السند يسقط المدين كافة حقوق التقديم والمطالبة والاحتجاج والاخطار بالامتناع عن الوفاء والمتعلقة بهذا السند .
                   </p>
                  <h3 class="text-center bold">محرر السند</h3>
                  <table>
                     <tr>
                        <th>اسم المدين</th>
                        <td colspan="4"> {{$contract->client->name}}</td>
                         <th>رقم الهوية</th>
                        <td colspan="4">{{$contract->client->national_id}}</td>
                     </tr>
                     <tr>
                        <th>مكان الوفاء</th>
                        <td colspan="4">بريدة</td>
                         <th>العنوان</th>
                        <td colspan="4">{{$contract->client->address}}</td>
                     </tr>
                      <tr class="height-modifay">
                        <th>التوقيع</th>
                        <td colspan="4"></td>
                         <th>البصمة</th>
                        <td colspan="4"></td>
                     </tr>
                     <tr>
                        <th>رقم الجوال</th>
                        <td colspan="4">{{$contract->client->phone}}</td>
                         <th>رقم الهاتف</th>
                        <td colspan="4">{{$contract->client->phone}}</td>
                     </tr>
                  </table>

               </div>
            </div>
         </div>
         <script src="js/bootstrap.min.js"></script>
            <script type="text/javascript">
                window.print();
            </script>

      </div>
   </body>
</html>

resources/views/admin/car_contracts/edit.blade.php
@extends('admin.layout.app')
@section('title')
تعديل العقد
{{ $contract->id }}
@endsection
@section('header')

@endsection

@section('content')

<!-- Basic Validation -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>تعديل العقد      {{ $contract->id }}</h2>
        <ul class="header-dropdown m-r--5">
          <a href="{{route('admin.car_contracts.index')}}">    <button class="btn btn-danger">كل العقود </button></a>
        </ul>
      </div>
      <div class="body">
        {!!Form::model($contract , ['route' => ['admin.car_contracts.update' , $contract->id] , 'method' => 'PATCH']) !!}
        @include('admin.car_contracts.form')
        {!!Form::close() !!}
      </div>
    </div>
  </div>
</div>


<!-- #END# Basic Validation -->
@endsection

resources/views/admin/car_contracts/index.blade.php
@extends('admin.layout.app')

@section('title')
  عرض  عقود السيارات
@endsection
@section('header')
  {{Html::style('admin/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}

@endsection
@section('content')
  <!-- Exportable Table -->
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>
            عرض عقود السيارات
          </h2>
          <ul class="header-dropdown m-r--5">
            <a href="{{route('admin.car_contracts.create')}}">   <button class="btn btn-success">إضافة عقد سياره جديد</button></a>
          </ul>
        </div>
        <div class="body">
          <table class="table table-bordered table-striped table-hover dataTable js-exportable">
            <thead>
            <tr>
              <th>#</th>
              <th>الوسيط</th>
              <th> العميل </th>
              <th> الضامن </th>
              <th> اجمالى المبلغ  المستحق </th>
              <th>المتبقى </th>
              <th> تاريخ بدء الاقساط </th>
              <th>الاقساط </th>
              <th>تقرير </th>
              <th>السندات </th>
              <th>العمليات</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
              <th>#</th>
              <th>الوسيط</th>
              <th> العميل </th>
              <th> الضامن </th>
              <th> اجمالى المبلغ  المستحق </th>
              <th>المتبقى </th>
              <th> تاريخ بدء الاقساط </th>
              <th>الاقساط </th>
              <th>تقرير </th>
              <th>السندات </th>
              <th>العمليات</th>
            </tr>
            </tfoot>
            <tbody>
            @foreach($car_contracts as $key=>$contract)
              <tr>
                <td>{{++$key}}</td>
                <td>{{$contract->mediator->name}}</td>
                <td>{{$contract->client->name}}</td>
                @if ($contract->kind=="client")
                  <?php
                  $id=$contract->clientv2_id;
                  $client=\App\Client::find($id);
                  ?>
                  <td>{{$client->name}}</td>
                @else
                  <?php
                  $id=$contract->guarantor_id;
                  $guarantor=\App\Guarantor::find($id);
                  ?>
                  <td>{{$guarantor->name}}</td>
                @endif


                  <td>{{$contract->amount+$contract->added_value+$contract->paid_amount}}</td>

                <td>
                  <?php
                  $not_paid=\App\Payment::where('contract_id',$contract->id)->where('pay',0)->sum('one_pay');
                  $rest=ceil($not_paid);
                  ?>
                  {{$rest}}

                </td>

                <td>{{$contract->start_date}}</td>
                <td>
                  <a href="{{route('admin.car_contracts.show',['id'=>$contract->id])}}" class="btn btn-primary btn-circle"><i  class="fa fa-list"></i></a>
                </td>
                  <td>
                    <a href="{{route('admin.car_contracts.report',['id'=>$contract->id])}}" class="btn btn-primary btn-circle"><i  class="fa fa-eye"></i></a>
                  </td>
                <td>
                  <a href="{{route('admin.car_contracts.client_sanad',['id'=>$contract->id])}}" style="margin-top:5px" class="btn btn-success ">سند العميل</a> 
                  <a href="{{route('admin.car_contracts.guarantor_sanad',['id'=>$contract->id])}}" style="margin-top:5px" class="btn btn-success ">سند الكفيل</a>

                </td>
                <td>
                  <a href="{{route('admin.car_contracts.print',['id'=>$contract->id])}}" class="btn btn-primary btn-circle"><i  class="fa fa-print"></i></a>

                  @if (Auth::user()->edit_contract==1)

                    <a href="{{route('admin.car_contracts.edit',['id'=>$contract->id])}}" class="btn btn-info btn-circle"><i class="fa fa-pencil"></i></a>
                   @endif
                    @if (Auth::user()->delete_contract==1)
                  <a href="#"  onclick="Delete({{$contract->id}})"  data-original-title="حذف" class="btn btn-danger btn-circle"><i  class="fa fa-trash-o"></i></a>
                  {!!Form::open( ['route' => ['admin.car_contracts.destroy',$contract->id] ,'id'=>'delete-form'.$contract->id, 'method' => 'Delete']) !!}
                  {!!Form::close() !!}
                     @endif
                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- #END# Exportable Table -->

@endsection

@section('footer')
  <script>
    function Delete(id) {
      var item_id=id;
      console.log(item_id);
      swal({
        title: "هل أنت متأكد ",
        text: "هل تريد حذف هذا العقد ؟",
        icon: "warning",
        buttons: ["الغاء", "موافق"],
        dangerMode: true,

      }).then(function(isConfirm){
        if(isConfirm){
          document.getElementById('delete-form'+item_id).submit();
        }
        else{
          swal("تم االإلفاء", "حذف  المستخدم تم الغاؤه",'info',{buttons:'موافق'});
        }
      });
    }
  </script>


{!!Html::script('admin/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')!!}
{!!Html::script('admin/plugins/jquery-datatable/extensions/export/jszip.min.js')!!}
{!!Html::script('admin/plugins/jquery-datatable/extensions/export/pdfmake.min.js')!!}
{!!Html::script('admin/plugins/jquery-datatable/extensions/export/vfs_fonts.js')!!}
{!!Html::script('admin/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')!!}
{!!Html::script('admin/plugins/jquery-datatable/extensions/export/buttons.print.min.js')!!}


@endsection

@section('data-table')

  <script type="text/javascript"
          src="https://cdn.datatables.net/v/bs/dt-1.10.18/r-2.2.2/datatables.min.js"></script>
  <script type="text/javascript"
          src="{{asset('admin/js/plugins/tables/datatables/datatables.min.js')}}"></script>
  <script type="text/javascript"
          src="{{asset('admin/js/plugins/tables/datatables/extensions/buttons.min.js')}}"></script>
  <script type="text/javascript"
          src="{{asset('admin/js/plugins/forms/selects/select2.min.js')}}"></script>
  <script type="text/javascript"
          src="{{asset('admin/js/plugins/datatables_extension_buttons_init.js')}}"></script>
@endsection