routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.layout.login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(array('prefix' => 'dashboard','as'=>'admin.' ,'middleware' => 'auth'), function() {

    Route::get('/', 'indexController@index')->name('layout.main');

    Route::resource('users', 'userController');
    Route::resource('guarantors', 'guarantorController');
    Route::resource('clients', 'clientController');
    Route::resource('mediators', 'mediatorController');
    Route::resource('settings', 'settingController');

    Route::resource('clearances', 'clearanceController');
    Route::resource('car_contracts', 'car_contractController');
    Route::resource('card_contracts', 'card_contractController');
    Route::any('/card_sadad/{id}','card_contractController@sadad' )->name('card_contracts.sadad');

    Route::post('/sadad-qests/{id}','card_contractController@qest_sadad' )->name('card_contracts.sadad_qests');
    Route::any('/sadad-cars/{id}','car_contractController@qest_sadad' )->name('car_contracts.sadad_qests');


    Route::get('/card','card_contractController@qast' )->name('card_contracts.qests');

    Route::get('/sadad/{id}','car_contractController@sadad' )->name('car_contracts.sadad');
    Route::get('/card_report/{id}','card_contractController@report' )->name('card_contracts.report');

    Route::get('/report/{id}','car_contractController@report' )->name('car_contracts.report');
    Route::get('/contract/{id}','car_contractController@print' )->name('car_contracts.print');
    Route::get('/card_contract/{id}','card_contractController@print' )->name('card_contracts.print');

    Route::get('/client_sanad/{id}','car_contractController@client_sanad' )->name('car_contracts.client_sanad');
    Route::get('/guarantor_sanad/{id}','car_contractController@guarantor_sanad' )->name('car_contracts.guarantor_sanad');

    Route::get('/card_client_sanad/{id}','card_contractController@client_sanad' )->name('card_contracts.client_sanad');
    Route::get('/card_guarantor_sanad/{id}','card_contractController@guarantor_sanad' )->name('card_contracts.guarantor_sanad');
    Route::any('/collected_premiums','ReportController@premiums')->name('reports.collected_premiums');

});

resources/views/admin/layout/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>برنامج التقسيط - @yield('title')</title>
    <!-- Favicon-->
     {{--<link rel="icon" href="{{asset('admin/images/logo.png')}}"> --}}

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Changa" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

    <link href="{{asset('admin/hijri-calender/css/jquery.calendars.picker.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/hijri-calender/css/hijri.css')}}" rel="stylesheet" type="text/css">
    <!-- Multi Select Css -->

      {!!Html::style('admin/plugins/multi-select/css/multi-select.css')!!}
    <!-- Bootstrap Core Css -->
   {!!Html::style('admin/plugins/bootstrap/css/bootstrap.min.css')!!}
    <!-- Waves Effect Css -->
    {!!Html::style('admin/plugins/node-waves/waves.min.css')!!}
    <!-- Animation Css -->
    {!!Html::style('admin/plugins/animate-css/animate.min.css')!!}
    <!-- Custom Css -->
    {!!Html::style('admin/css/style.min.css')!!}
    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    {!!Html::style('admin/css/themes/theme-red.min.css')!!}
    {!!Html::style('admin/css/rtl.css')!!}

    {!!Html::style('admin/css/pro.css')!!}
    {!!Html::style('admin/cus/sweetalert.css')!!}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.css">
   {!!Html::style('admin/cus/final-style.css')!!}
    <style>
    .navbar {
        background-color: #FF9800 ;
    }
    .sidebar .user-info {
        height: 82px;
    }    
        .alert.bg-red{
        background-color: rgba(47, 36, 13, 0.43) ;
}
        
div.dataTables_wrapper div.dataTables_info {
    color: #ffffff;
}
    </style>

    @yield('header')
</head>

<body class="theme-red">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>رجاءً انتظر...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->

    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->

    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            {{--<div class="nav-logo">--}}
                    {{--<img src="{{asset('admin/images/logo.png')}}" alt="">--}}
                {{--</div>--}}
            <div class="navbar-header">
                <a href="javascript:void(0);" class="bars"></a>
                <form id="logout-form" action="/logout" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
                <a class="navbar-brand" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();"> <i class="fa fa-power-off"></i> </a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                </ul>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->

    <section>
        <!-- Left Sidebar -->
        <aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                {{-- <div class="image">
                <img src="{{url('admin/images/user.png')}}" width="48" height="48" alt="User" />
            </div> --}}
            <div class="info-container">
                <div class="name ar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{Auth::user()->name}}</div>
                <div class="email ar">{{Auth::user()->email}}</div>
                <div class="btn-group user-helper-dropdown">
                    <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                    <ul class="dropdown-menu pull-left">
                        <form id="logout-form" action="/logout" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                        <li><a class="ar" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();" href="{{url('/logout')}}"><i class="material-icons">input</i>تسجيل الخروج</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                <ul class="list">
                    <li class="header">القائمة الرئيسية</li>
                    @include('admin.layout.nav')
                </ul>
            </div>
            <!-- #Menu -->
        </aside>
        <!-- #END# Left Sidebar -->
    </section>

    <section class="content">
        <div class="container-fluid">
            @yield('content')
        </div>
    </section>
    <!-- Multi Select Plugin Js -->


    <!-- Jquery Core Js -->
    {!!Html::script('admin/plugins/jquery/jquery.min.js')!!}
    <!-- Bootstrap Core Js -->
    {!!Html::script('admin/plugins/bootstrap/js/bootstrap.min.js')!!}
    <!-- Select Plugin Js -->
    {!!Html::script('admin/plugins/bootstrap-select/js/bootstrap-select.min.js')!!}
    <!-- Slimscroll Plugin Js -->
    {!!Html::script('admin/plugins/jquery-slimscroll/jquery.slimscroll.min.js')!!}
    <!-- Waves Effect Plugin Js -->
    {!!Html::script('admin/plugins/node-waves/waves.min.js')!!}
    <!-- Custom Js -->
    {!! Html::script('/admin/plugins/forms/selects/select2.min.js') !!}
    <script>

        $(document).ready(function() {
            $('.js-example-basic-single').select2();
        });

    </script>
    {!!Html::script('admin/js/admin.js')!!}
    {!!Html::script('admin/js/demo.js')!!}
    {!!Html::script('admin/cus/sweetalert.min.js')!!}
    <script type="text/javascript">
    var lis = $('.check_active');

    lis.each(function(index){
        if($(this).attr('href') === "{!!url('/')!!}" + window.location.pathname){
            $(this).parent().addClass('active');
            $(this).parent().parent().parent().addClass('active');

        }
        // console.log($(this).attr('href'));
    });
    </script>
    <script type="text/javascript">
    $(window).load(function() {
        if($( window ).width() < 481){
            $('.dt-buttons').hide();
        }
    });
    </script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    @include('sweet::alert')


    @if(Session::has('success'))
        <script>
            new Noty({
                type: 'info',
                layout: 'topRight',
                text: '{!! Session::get('success') !!}'
            }).show();
        </script>
    @elseif(Session::has('error'))
        <script>
            new Noty({
                type: 'error',
                layout: 'topRight',
                text: '{!! Session::get('error') !!}'
            }).show();
        </script>
    @endif

    @yield('footer')

    @yield('data-table')

@stack('scripts')



</body>
</html>

resources/views/admin/layout/home.blade.php
@extends('admin.layout.app')

@section('title')

الصفحه الرئيسه
@endsection
@section('header')
      {{Html::style('admin/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}
@endsection
@section('content')
    <!-- Widgets -->
    <div class="row clearfix">



<div class="alert bg-red">هناك عدد {{$payments}} اقساط شارف على السداد<a href="{{route('admin.card_contracts.qests')}}"> تابع الاقساط </a>   </div>






    </div>
    <!-- #END# Widgets -->

@endsection

@section('footer')
    {!!Html::script('admin/plugins/jquery-countto/jquery.countTo.js')!!}
    <script type="text/javascript">
        $('.count-to').countTo();

    </script>

            <script>

    {!!Html::script('admin/plugins/raphael/raphael.min.js')!!}
   {!!Html::script('admin/plugins/morrisjs/morris.js')!!}


    <!-- Chart Plugins Js -->
    {!!Html::script('admin/plugins/chartjs/Chart.bundle.js')!!}

  <!-- Custom Js -->

    {!!Html::script('admin/js/pages/charts/chartjs.js')!!}

  <!-- Demo Js -->



    <!-- Jquery Knob Plugin Js -->
    {!!Html::script('admin/plugins/jquery-knob/jquery.knob.min.js')!!}

    {!!Html::script('admin/js/pages/charts/jquery-knob.js')!!}





@endsection

resources/views/admin/layout/login.blade.php
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <title>تسجيل الدخول - برنامج التقسيط</title>
  <!-- Favicon-->
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Changa" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

  <!-- Bootstrap Core Css -->
  {!!Html::style('admin/plugins/bootstrap/css/bootstrap.css')!!}

  <!-- Waves Effect Css -->
  {!!Html::style('admin/plugins/node-waves/waves.css')!!}

  <!-- Animation Css -->
  {!!Html::style('admin/plugins/animate-css/animate.css')!!}

  <!-- Custom Css -->
  {!!Html::style('admin/css/style.css')!!}

  <style>
*
{
    font-family: 'Changa', sans-serif;
}
  </style>

</head>

<body class="login-page" dir="rtl">
  <div class="flex-img">
     <img src="{{asset('admin/images/login.svg')}}" alt="">
      <div class="login-box">
    <div class="card">
      <div class="body">

        <form id="sign_in" role="form" method="POST" action="{{route('login')}}">
          @if (count($errors) > 0)
          <div class="alert alert-info">
            <ul>
              @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif

          {{ csrf_field() }}
            
            <div class="logo">
                <img src="{{asset('admin/images/logo.jpg')}}">
            </div>
          <div class="msg">تسجيل الدخول</div>
          <div class="input-group">
            <span class="input-group-addon">
              <i class="material-icons">email</i>
            </span>
            <div class="form-line">
              <input type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"  name="email" value="{{ old('email') }}"  placeholder="Email" required autofocus>
            </div>
          </div>
          <div class="input-group">
            <span class="input-group-addon">
              <i class="material-icons">lock</i>
            </span>
            <div class="form-line">
              <input type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" placeholder="Password" required>
            </div>

          </div>
          <div class="row">

          
              <button class="btn btn-block bg-blue waves-effect" type="submit">دخول</button>
          
          </div>

        </form>
      </div>
    </div>
  </div>
  </div>

  <!-- Jquery Core Js -->
  {!!Html::script('admin/plugins/jquery/jquery.min.js')!!}

  <!-- Bootstrap Core Js -->
  {!!Html::script('admin/plugins/bootstrap/js/bootstrap.js')!!}

  <!-- Waves Effect Plugin Js -->
  {!!Html::script('admin/plugins/node-waves/waves.js')!!}

  <!-- Validation Plugin Js -->
  {!!Html::script('admin/plugins/jquery-validation/jquery.validate.js')!!}

  <!-- Custom Js -->
  {!!Html::script('admin/js/admin.js')!!}
  {!!Html::script('admin/js/pages/examples/sign-in.js"')!!}
</body>

</html>

resources/views/admin/layout/main.blade.php
@extends('admin.app')

@section('title')
الرئيسية
@endsection
@section('header')
@endsection
@section('content')
<div class="text-center">
  <a href="#" class="text-center">
    <img src="/admin/images/logo.png" alt="logo" style="width:50%;"/>
  </a>
</div>
@endsection

@section('footer')

@endsection

resources/views/admin/layout/nav.blade.php
<li>
  <a class="check_active" href="{{route('admin.layout.main')}}">
    <i class="material-icons">home</i>
    <span>الصفحه الرئيسه والاحصائيات</span>
  </a>

</li>
@if ( auth()->user()->is_admin == 1)


  <li>
    <a href="javascript:void(0);" class="menu-toggle">
      <i class="material-icons">assignment_ind</i>
      <span>المستخدمين</span>
    </a>
    <ul class="ml-menu">
      <li >
        <a class="check_active" href="{{route('admin.users.index')}}">

          <span> عرض المستخدمين</span>
        </a>
      </li>
      <li >
        <a  class="check_active" href="{{route('admin.users.create')}}">

          <span>اضافه مستخدم جديد</span>
        </a>
      </li>
    </ul>
  </li>

@endif

  <li>
    <a href="javascript:void(0);" class="menu-toggle">
      <i class="material-icons">assignment_ind</i>
      <span>العملاء</span>
    </a>
    <ul class="ml-menu">
      <li >
        <a class="check_active" href="{{route('admin.clients.index')}}">

          <span> عرض العملاء</span>
        </a>
      </li>
      <li >
        <a  class="check_active" href="{{route('admin.clients.create')}}">

          <span>اضافه عميل جديد</span>
        </a>
      </li>
    </ul>
  </li>


  <li>
    <a href="javascript:void(0);" class="menu-toggle">
      <i class="material-icons">assignment_ind</i>
      <span>الكفلاء</span>
    </a>
    <ul class="ml-menu">
      <li >
        <a class="check_active" href="{{route('admin.guarantors.index')}}">

          <span> عرض الكفلاء</span>
        </a>
      </li>
      <li >
        <a  class="check_active" href="{{route('admin.guarantors.create')}}">

          <span>اضافه كفيل جديد</span>
        </a>
      </li>
    </ul>
  </li>

  <li>
    <a href="javascript:void(0);" class="menu-toggle">
      <i class="material-icons">assignment_ind</i>
      <span>الوسطاء-الطرف الاول</span>
    </a>
    <ul class="ml-menu">
      <li >
        <a class="check_active" href="{{route('admin.mediators.index')}}">

          <span> عرض الوسطاء</span>
        </a>
      </li>
      <li >
        <a  class="check_active" href="{{route('admin.mediators.create')}}">

          <span>اضافه وسيط جديد</span>
        </a>
      </li>
    </ul>
  </li>


  <li>
    <a href="javascript:void(0);" class="menu-toggle">
      <i class="material-icons">assignment_ind</i>
      <span>المخالصات</span>
    </a>
    <ul class="ml-menu">
      <li >
        <a class="check_active" href="{{route('admin.clearances.index')}}">

          <span> عرض المخالصات</span>
        </a>
      </li>
      <li >
        <a  class="check_active" href="{{route('admin.clearances.create')}}">

          <span>اضافه مخالصه  جديد</span>
        </a>
      </li>
    </ul>
  </li>


  <li>
    <a href="javascript:void(0);" class="menu-toggle">
      <i class="material-icons">assignment_ind</i>
      <span>العقود</span>
    </a>
    <ul class="ml-menu">
      <li >
        <a class="check_active" href="{{route('admin.car_contracts.index')}}">

          <span> عقود السيارات</span>
        </a>
      </li>
      <li >
        <a  class="check_active" href="{{route('admin.card_contracts.index')}}">

          <span>عقود بطاقات الشحن</span>
        </a>
      </li>
    </ul>
  </li>



@if ( auth()->user()->is_admin == 1)
<li>
  <a href="javascript:void(0);" class="menu-toggle">
    <i class="material-icons">assignment_ind</i>
    <span>الاعدادات</span>
  </a>
  <ul class="ml-menu">
    <li >
      <a class="check_active" href="{{route('admin.settings.edit',1)}}">

        <span> عرض الاعدادت</span>
      </a>
    </li>

  </ul>
</li>
  @endif

  @if ( auth()->user()->is_admin == 1)
<li>
  <a href="javascript:void(0);" class="menu-toggle">
    <i class="material-icons">assignment_ind</i>
    <span>التقارير</span>
  </a>
  <ul class="ml-menu">
    <li >
      <a class="check_active" href="{{route('admin.reports.collected_premiums')}}">

        <span>  تقرير الاقساط المحصلة</span>
      </a>
    </li>

  </ul>
</li>
  @endif